"""`gt feedback` — build a prefilled GitHub Discussions URL for low-friction reports.

The CLI surface (`gt feedback` in `cli.py`) collects a corpus snapshot plus
the user's free-text note, renders a Markdown body, runs it through the
existing secret-redaction filter from `_logging.py`, URL-encodes it into a
"new discussion" link, and opens the browser. Nothing leaves the user's
machine until they hit Submit on the rendered GitHub page.

This module is pure data + string assembly so it's testable without a
browser, network, or DB. The CLI command in `cli.py` is the only place that
calls `webbrowser.open` or touches a live `sqlite3.Connection`.
"""

from __future__ import annotations

import platform
import sqlite3
import sys
from dataclasses import dataclass
from typing import Any
from urllib.parse import urlencode

from . import __version__, _logging
from .store import queries as q
from .target import load_targets

DEFAULT_REPO = "ChristopherDavenport/github-twin"


@dataclass(frozen=True)
class EnvInfo:
    gt_version: str
    python_version: str
    platform: str


@dataclass(frozen=True)
class TargetSnapshot:
    kind: str
    name: str
    artifacts: dict[str, int]
    chunks: dict[str, int]
    vectors: int
    pending_embed: int


def collect_env() -> EnvInfo:
    return EnvInfo(
        gt_version=__version__,
        python_version=sys.version.split()[0],
        platform=platform.platform(),
    )


def collect_corpus(conn: sqlite3.Connection) -> list[TargetSnapshot]:
    """Snapshot every target's artifact/chunk/vector counts. Read-only."""
    out: list[TargetSnapshot] = []
    for tg in load_targets(conn):
        assert tg.id is not None
        s = q.stats(conn, target_id=tg.id)
        out.append(
            TargetSnapshot(
                kind=tg.kind,
                name=tg.name,
                artifacts=dict(s["artifacts"]),
                chunks=dict(s["chunks"]),
                vectors=int(s["vectors"]),
                pending_embed=int(s["pending_embed"]),
            )
        )
    return out


def _embed_summary(cfg_embed: Any) -> str:
    """Render the per-DB embed commitment in one line. `cfg_embed` is the
    `cfg.embed` block from `Config` — typed as Any here so this module
    has no compile-time dependency on the pydantic-settings model."""
    backend = getattr(cfg_embed, "backend", "?")
    model = getattr(cfg_embed, "model", "?")
    dim = getattr(cfg_embed, "dim", "?")
    return f"{backend} / {model} (dim={dim})"


def render_body(
    env: EnvInfo,
    embed_summary: str,
    corpus: list[TargetSnapshot],
    user_note: str,
) -> str:
    """Compose the Markdown discussion body. Not yet redacted — caller
    pipes the return value through `scrub_secrets`."""
    lines: list[str] = []
    lines.append("## Feedback")
    lines.append("")
    note = user_note.strip()
    lines.append(note if note else "_(no free-text note provided)_")
    lines.append("")
    lines.append("## Environment")
    lines.append("")
    lines.append(f"- `gt` version: `{env.gt_version}`")
    lines.append(f"- Python: `{env.python_version}`")
    lines.append(f"- Platform: `{env.platform}`")
    lines.append(f"- Embed: `{embed_summary}`")
    lines.append("")
    lines.append("## Corpus")
    lines.append("")
    if not corpus:
        lines.append("_(no targets — `gt init` has not been run)_")
    else:
        for snap in corpus:
            artifact_total = sum(snap.artifacts.values())
            chunk_total = sum(snap.chunks.values())
            lines.append(
                f"- **{snap.kind} `{snap.name}`** — "
                f"{artifact_total} artifacts, {chunk_total} chunks, "
                f"{snap.vectors} vectors "
                f"(pending embed: {snap.pending_embed})"
            )
    lines.append("")
    lines.append("---")
    lines.append("_Generated by `gt feedback`._")
    return "\n".join(lines)


def scrub_secrets(text: str) -> str:
    """Redact secret-shaped substrings from `text` using the same filter
    the logging subsystem applies to log records. Defense in depth: the
    payload is assembled from stats columns (artifact counts, paths,
    target names) that should never contain a token, but a token could
    in theory land in a target name or a free-text note. We scrub
    anyway."""
    flt = _logging.SecretRedactingFilter()
    return flt._scrub(text)  # noqa: SLF001 — intentional reuse of internal scrubber


def build_discussion_url(
    *,
    body: str,
    title: str | None = None,
    category: str | None = None,
    repo: str = DEFAULT_REPO,
) -> str:
    """Build a GitHub "new discussion" URL with prefilled body/title/category.

    GitHub accepts `title`, `body`, and `category` as query params on
    `/discussions/new`. Body is URL-encoded; GitHub renders it as
    Markdown in the form."""
    params: dict[str, str] = {"body": body}
    if title:
        params["title"] = title
    if category:
        params["category"] = category
    return f"https://github.com/{repo}/discussions/new?" + urlencode(params)
