r"""`CLAUDE.md` template emitted by `gt init-claude-md`.

The template wires Claude Code to github-twin's MCP tools by telling
the agent *when* to call each one. Variables:

- `{target_name}` — the github-twin target (user login, org name, or
  'owner/name'). Falls back to `(none — run \`gt init\` first)`.
- `{server_name}` — MCP server name as registered in
  `.claude.json`. Default `github-twin`.
- `{date}` — ISO date, for the generated header.

Format strings use `str.format(**ctx)` so curly braces inside the
template body are escaped as `{{` / `}}`.
"""

from __future__ import annotations

CLAUDE_MD_TEMPLATE = """\
# CLAUDE.md

> Generated by `github-twin init-claude-md` on {date}.
> Target: **{target_name}**. MCP server: **{server_name}**.
> Edit freely — this is your file.

## What github-twin gives you

A retrieval surface over {target_name}'s GitHub history (commits,
review comments, files-at-HEAD). Use it to ground code-writing and
code-reviewing tasks in real past examples instead of inventing
plausible ones.

## At session start

Two calls give you the static context the rest of the session needs.
Make them once, treat the output as durable memory:

1. **`mcp__{server_name}__house_rules()`** — returns a Markdown block
   of distilled conventions (reviewer rules + code patterns). Prepend
   it to your working context.
2. **`mcp__{server_name}__developer_profile()`** — returns 2–3
   paragraphs describing {target_name}'s review voice. Useful when
   you're acting *as* {target_name}: writing reviews, leaving
   comments, predicting how a PR will land. Cached server-side, so
   repeat calls are cheap.

Both surfaces are static for the session unless `gt distill` /
`gt sync` runs in the meantime.

## When you're writing code (acting as {target_name})

Before producing a non-trivial diff:

- **`find_style_examples(query="...", scope="personal", k=5)`** —
  what does this person's code look like for this task? `scope="personal"`
  restricts the search to {target_name}'s own commits when the target
  is a single user; `scope="project"` restricts to the current repo
  when the target is repo-mode.
- **`find_applicable_rules(query="...", k=5)`** — distilled
  code-pattern rules that match the task. Returns the actual rule
  text + member examples, not just a count.
- **`find_code(query="...", language="...", path_glob="...")`** —
  full-file snippets from indexed source at HEAD. Best when you know
  approximately *where* in the codebase the relevant code lives.

## When you're reviewing code (in {target_name}'s voice)

Before drafting review comments:

- **`find_review_comments(diff_hunk="...", scope="personal", k=5)`**
  — past review comments on similar diffs. Mimic the tone and the
  concern set. `scope="personal"` pins the corpus to {target_name}.
- **`predict_review_outcome(diff_or_summary="...", k=20)`** —
  weighted prediction (approved / changes_requested / commented)
  over the nearest past PRs. Useful as a sanity check before
  recommending merge / block.
- **`summarize_review_patterns(language="scala", limit=20)`** — same
  source as `house_rules` but the raw list (with example quotes),
  useful when you need to dig into specifics rather than scan the
  Markdown block.

## Scope hints

The retrieval tools take a `scope` parameter that names the
memdir-style tier you're in:

- `scope="personal"` — restrict to {target_name}'s own
  commits / reviews. Sugar for `author_login={target_name}`.
- `scope="project"` — restrict to the current repository. Sugar for
  `repo=...` based on the target's repo (repo-mode only).
- `scope="all"` (default) — entire corpus.

Explicit `repo=` / `author_login=` arguments always win over `scope`.

## When things look stale

If retrieval is returning old PRs and missing recent activity:

```
uvx github-twin sync
```

That ingests new commits / reviews, summarizes any new code chunks,
and re-embeds anything pending. The MCP server's `sync` tool does
the same thing if you'd rather stay in-session.

## Going deeper

- `learning/` in this repo — concept walkthrough (RAG, ingest,
  chunking, embed, retrieve, distill, eval, putting it together).
- `README.md` — install, configuration, MCP wiring example, the
  full backends matrix.
- `getting_started.md` — end-to-end first-time-setup walkthrough.
"""


def render(*, target_name: str, server_name: str = "github-twin", date: str) -> str:
    """Render the template with concrete values. Keyword-only to keep
    the call site self-documenting."""
    return CLAUDE_MD_TEMPLATE.format(
        target_name=target_name,
        server_name=server_name,
        date=date,
    )
