r"""`CLAUDE.md` template emitted by `gt init-claude-md`.

Multi-target aware. The template lists every target the DB holds and
documents the `target=` parameter so callers know how to narrow when
they want one target's view in particular.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from github_twin.target import Target


CLAUDE_MD_TEMPLATE = """\
# CLAUDE.md

> Generated by `github-twin init-claude-md` on {date}.
> Targets: {target_list_inline}.
> MCP server: **{server_name}**.
> Edit freely — this is your file.

## What github-twin gives you

A retrieval surface over GitHub history across every target in this DB
({n_targets}: {target_list_bullets}). Use it to ground code-writing
and code-reviewing tasks in real past examples instead of inventing
plausible ones.

## Coalesce by default, narrow when needed

The retrieval tools coalesce across every target unless you pass
`target=NAME`. Each returned hit carries its `target` so you can see
where it came from. When you specifically want one target's view, pass
`target="..."`. When you want strictly the user-mode corpus, pass
`scope="personal"` — that resolves to the user-mode target and
prevents org-side mirrors of your own commits from re-entering the
sample.

## At session start

Two calls give you the static context the rest of the session needs:

1. **`mcp__{server_name}__house_rules()`** — distilled conventions
   (reviewer rules + code patterns) across every target. Pass
   `target="..."` to restrict.
2. **`mcp__{server_name}__developer_profile(scope="personal")`** — a
   2–3 paragraph profile of your own review voice, sourced strictly
   from the user-mode target if one exists. Cached server-side.

## When you're writing code

- **`find_style_examples(query="...", scope="personal", k=5)`** —
  what does your own code look like for this task?
- **`find_applicable_rules(query="...", k=5)`** — distilled
  code-pattern rules across every target. Pass `target="ORG"` to
  narrow.
- **`find_code(query="...", language="...", path_glob="...")`** —
  full-file snippets at HEAD. Coalesces across targets; each hit
  carries its target name.

## When you're reviewing code

- **`find_review_comments(diff_hunk="...", scope="personal", k=5)`**
  — past review comments on similar diffs. `scope="personal"` pins
  the corpus to the user-mode target.
- **`predict_review_outcome(diff_or_summary="...", k=20)`** —
  weighted prediction over the nearest past PRs.
- **`summarize_review_patterns(language="scala", limit=20)`** — raw
  rule list with example quotes.

## Targets in this DB

{target_table}

## When things look stale

```
uvx github-twin sync
```

That ingests new commits + review comments for every target,
summarizes new code chunks, and re-embeds anything pending. Pass
`--target NAME` to limit to one.

## Going deeper

- `README.md` — install, configuration, MCP wiring example.
- `getting_started.md` — end-to-end first-time-setup walkthrough.
"""


def _format_target_table(targets: list[Target]) -> str:
    if not targets:
        return "_(none — run `gt init` first)_"
    lines = ["| target | kind | external_id |", "|---|---|---|"]
    for t in targets:
        lines.append(f"| `{t.name}` | {t.kind} | {t.external_id} |")
    return "\n".join(lines)


def _format_inline_targets(targets: list[Target]) -> str:
    if not targets:
        return "**(none)**"
    return ", ".join(f"**{t.name}** ({t.kind})" for t in targets)


def _format_bullets(targets: list[Target]) -> str:
    if not targets:
        return "none"
    return ", ".join(t.name for t in targets)


def render(
    *,
    targets: list[Target] | None = None,
    target_name: str | None = None,
    server_name: str = "github-twin",
    date: str,
) -> str:
    """Render the template.

    Accepts either a list of `Target` objects (preferred) or, for
    backwards compatibility in single-target callers, a `target_name`
    string.
    """
    if targets is None:
        if target_name:
            # Lightweight stand-in so the template can format consistently
            # without importing the full Target dataclass at call time.
            from dataclasses import dataclass

            @dataclass
            class _Stub:
                name: str
                kind: str = "?"
                external_id: int = 0

            targets = [_Stub(name=target_name)]  # type: ignore[list-item]
        else:
            targets = []

    return CLAUDE_MD_TEMPLATE.format(
        date=date,
        server_name=server_name,
        n_targets=len(targets),
        target_list_inline=_format_inline_targets(targets),
        target_list_bullets=_format_bullets(targets),
        target_table=_format_target_table(targets),
    )
